{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "metrics-accumulator.fullname" . }}
  labels:
    {{- include "metrics-accumulator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "metrics-accumulator.selectorLabels" . | nindent 6 }}
  {{- if .Values.networkPolicy.policyTypes }}
  policyTypes:
    {{- range .Values.networkPolicy.policyTypes }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }} 