apiVersion: v2
name: aws-alb-gateway
description: Manage AWS Load Balancer Controller Gateway API resources for EKS.
type: application
version: 0.1.1
appVersion: "0.1.1"
keywords:
  - aws
  - eks
  - alb
  - gateway-api
  - aws-load-balancer-controller
home: https://kubernetes-sigs.github.io/aws-load-balancer-controller/
sources:
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller
maintainers:
  - name: platform-engineering
